# Generated by Django 3.2.16 on 2022-12-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='imagem',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='pontos/'),
        ),
    ]
