# Generated by Django 3.2.16 on 2022-12-23 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_local_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='senha',
        ),
    ]
