# Generated by Django 3.2.16 on 2022-12-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_local_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='pontos/'),
        ),
    ]
